project:
  type: website

website:
  title: "Glasgow Archery League"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Events/2024-5/events.qmd
        text: 2024-5 Events
      - href: Events/2025-6/events.qmd
        text: 2025-6 Events (Current)

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual
